# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books_app', '0002_auto_20171021_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='thisReview',
        ),
    ]
